name: Scout Audit

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  scout-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Run Scout
        uses: coinfabrik/scout-actions@v3.2
        with:
          working_directory: .
          scout_extra_args: "--filter known-vulnerabilities,avoid-panic-error"
          verbose: true
          comment_pr: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
